// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGH8veNI4YW1g5zwgYkMg-bcmb8wMSbI',
    appId: '1:739712242269:android:5cfaf4d308b68da8bef3b4',
    messagingSenderId: '739712242269',
    projectId: 'mindcompass-e4703',
    storageBucket: 'mindcompass-e4703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIcOifufYqvGwUO5hZrt1eA4Z6leUA0M8',
    appId: '1:739712242269:ios:a633c4b6f4eca01ebef3b4',
    messagingSenderId: '739712242269',
    projectId: 'mindcompass-e4703',
    storageBucket: 'mindcompass-e4703.appspot.com',
    iosBundleId: 'com.example.mindcompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIcOifufYqvGwUO5hZrt1eA4Z6leUA0M8',
    appId: '1:739712242269:ios:cf08789669a36325bef3b4',
    messagingSenderId: '739712242269',
    projectId: 'mindcompass-e4703',
    storageBucket: 'mindcompass-e4703.appspot.com',
    iosBundleId: 'com.example.mindcompass.RunnerTests',
  );
}
